### ISSUE TITLE
Put every swear word in a seperate file

### ISSUE THREAD

**Issue by legoboy0215** [Awzaw/AntiSpamPro#1]
Please do that.

**Comment by Awzaw** [comment]
Why? The idea is plug and play censoring, and to avoid people messing with
the filter. If you want to ban or replace specific words you can use
chatcensor, but as it is this is an effective filter, with very few false
positives.
On 1 Jul 2016 11:56 a.m., "legoboy0215" notifications@github.com wrote:

Please do that.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/Awzaw/AntiSpamPro/issues/1, or mute the thread
https://github.com/notifications/unsubscribe/AJ9CXLPT5yD2fpo5Nov-zcCap2VvMVVSks5qROREgaJpZM4JC_vN
.

**Comment by legoboy0215** [comment]
I mean like swearword.json and list all of them there. Parse the file when the plugin is loaded.

**Comment by Awzaw** [comment]
I don't think that would improve performance, but I'll probably put them in
an external file if I add commands to add/remove words

**Comment by NML32** [comment]
I'll probably start using the plugin once the swear words are in a separate file so I can edit them. I was getting too many false positives.

**Comment by Awzaw** [comment]
Swear words are now in swearwords.yml
